steps:
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - '${_REPO}'
  - name: gcr.io/cloud-builders/git
    args:
      - '-c'
      - >-
        git diff HEAD~ HEAD --quiet --name-only -- Proxies/${_PROXY_FOLDER} ||
        touch execute.txt || echo 'No changes'
    id: Check for changes
    entrypoint: bash
  - name: gcr.io/cloud-builders/gcloud
    args:
      - "-c"
      - |
        gcloud auth print-access-token > token.txt
        echo "Token saved to token.txt"
    id: Save token to file
    entrypoint: bash
  - name: gcr.io/cloud-builders/mvn
    args: 
      - '-c'
      - | 
        cd examples/apigee-cicd-maven-plugin/clientes/clientes-v1 && \
        mvn -ntp install -P prod -Dorg=rolandos-appmod-demos -Denv=prod-test -Dbearer=${cat /workspace/token.txt}
    id: Create and Deploy revision
    entrypoint: bash
timeout: 1600s
options:
  logging: CLOUD_LOGGING_ONLY
  env: ['bearer=$(gcloud auth print-access-token)']
